version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
